version: '3.8'
services:
  ros_noetic:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vehicle_dashboard_local
    image: vehicle_dashboard
    networks:
      default: null
    ports:
      - "8000:8000"
    command: ["bash", "-c", "while true; do sleep 1000; done"]
networks:
  default:
    name: vehicle-dashboad_default